services:
  snowball_legacy.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5001:8080"
    depends_on:
      - postgres_db
  
  postgres_db:
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: xM6k!5aX4m
        POSTGRES_DB: dev_snowball
    ports:
        - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data

  certbot:
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/letsencrypt
    command: certonly
      --non-interactive
      --agree-tos
      --email nikl808@github
      --preferred-challenges dns
      --authenticator dns-duckdns
      --dns-duckdns-token bf3c271b-754e-4774-a34e-fa7594c11d8d
      --dns-duckdns-no-txt-restore
      --dns-duckdns-propagation-seconds 15
      -d "old-snowballru.duckdns.org"
      -d "*.old-snowballru.duckdns.org"

  proxy:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
        - ./letsencrypt:/etc/letsencrypt
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"
        - "443:443"
    depends_on:
        - snowball_legacy.server
    extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
    postgres-data: