services:
  snowball_legacy.server:
    image: ${DOCKER_REGISTRY-}snowballlegacyserver
    build:
      context: .
      dockerfile: Snowball_Legacy.Server/Dockerfile
 
  postgres_db:
    container_name: postgres
    image: postgres:latest
  
  certbot:
    container_name: certbot
    image: "infinityofspace/certbot_dns_duckdns:latest"

  proxy:
    container_name: nginx
    image: nginx:mainline
