services:
  snowball_legacy.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - postgres_db
  
  postgres_db:
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: xM6k!5aX4m
        POSTGRES_DB: dev_snowball
    ports:
        - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data
 
  proxy:
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"
  
volumes:
    postgres-data: