networks:
    snowball-server-dev:
        driver: bridge
services:
    app:
        container_name: Snowball_Legacy.Server
        build:
            context: .    
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - snowball-server-dev
        depends_on:
            - postgres_db

    postgres_db:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: xM6k!5aX4m
            POSTGRES_DB: dev_snowball
        ports:
            - "5432:5432"
        networks:
            - snowball-server-dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: 