// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Snowball_Legacy.Server.Contexts;

#nullable disable

namespace Snowball_Legacy.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250218114700_GameInfo")]
    partial class GameInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Snowball_Legacy.Server.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Snowball_Legacy.Server.Models.GameFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("File")
                        .HasColumnType("bytea");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameFile");
                });

            modelBuilder.Entity("Snowball_Legacy.Server.Models.GameInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DiskNumber")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("TitlePictureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("TitlePictureId");

                    b.ToTable("GameInfo");
                });

            modelBuilder.Entity("Snowball_Legacy.Server.Models.GamePicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameInfoId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("GameInfoId");

                    b.ToTable("GamePicture");
                });

            modelBuilder.Entity("Snowball_Legacy.Server.Models.GameFile", b =>
                {
                    b.HasOne("Snowball_Legacy.Server.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Snowball_Legacy.Server.Models.GameInfo", b =>
                {
                    b.HasOne("Snowball_Legacy.Server.Models.Game", "Game")
                        .WithOne("GameInfo")
                        .HasForeignKey("Snowball_Legacy.Server.Models.GameInfo", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Snowball_Legacy.Server.Models.GamePicture", "TitlePicture")
                        .WithMany()
                        .HasForeignKey("TitlePictureId");

                    b.Navigation("Game");

                    b.Navigation("TitlePicture");
                });

            modelBuilder.Entity("Snowball_Legacy.Server.Models.GamePicture", b =>
                {
                    b.HasOne("Snowball_Legacy.Server.Models.GameInfo", null)
                        .WithMany("ScreenShoots")
                        .HasForeignKey("GameInfoId");
                });

            modelBuilder.Entity("Snowball_Legacy.Server.Models.Game", b =>
                {
                    b.Navigation("GameInfo");
                });

            modelBuilder.Entity("Snowball_Legacy.Server.Models.GameInfo", b =>
                {
                    b.Navigation("ScreenShoots");
                });
#pragma warning restore 612, 618
        }
    }
}
